### ISSUE TITLE
Getting a Variant.formatter for classes that contain an object that already has a Variant.formatter

### ISSUE THREAD

**Issue by makoConstruct** [julienrf/play-json-derived-codecs#11]
It does not seem to be allowed for reasons I do not understand.

consider the following:
```
import julienrf.variants.Variants

sealed trait SA
case class Saone(a:Int) extends SA
implicit val saFormat:Format[SA] = Variants.format[SA]

sealed trait SB
case class Sbone(a:Saone) extends SB
case class Sbomo(note:String) extends SB
implicit val sbFormat:Format[SB] = Variants.format[SB]

val written = sbFormat.writes(Sbomo("hogmaster"))
```
There is a Saone inside one of the SBs, but this should not be a problem, as we already have an implicit formatter for SAs. However, we get a compiler error complaining `No implicit Reads for controllers.Application.Saone available.` on the line of the definition of sbFormat.

Oddly, removing Format[_] type annotations stops the compile error, but using the sbFormat on written's line then elicits a `scala.MatchError: Sbomo(hogmaster)` coming from the line on which the sbFormatter was defined(presumably it's happening somewhere in the macro expansion).

**Comment by takiri** [comment]
Hi, I'm getting the same problem.
Could you find a solution back then ?
(As i understand it, Format should provide a Read and a Write, shouldn't it?)

Thanks

**Comment by julienrf** [comment]
Hi, I’m sorry I didn’t take time to solve this problem yet.

**Comment by rcaloras** [comment]
FYI recently ran into this as well. Was able to work around with my model though thankfully.

**Comment by takiri** [comment]
Could you tell us a bit about your workaround please? (I actually got rid of my second trait, so don't have to deal with this problem anymore but i'm very interested in it ! )

**Comment by rcaloras** [comment]
Not really a work around I guess. I had to do the same thing and either get rid of one of my traits or write out the entire Format manually. I went in favor of writing out the Format function myself. 

So much boiler plate! Would love to just generate it all.
