### ISSUE TITLE
It is unclear how to use the library

### ISSUE THREAD

**Issue by danslapman** [julienrf/play-json-derived-codecs#32]
Hi!
I just curious about how make this library working. I have this code:

`
import julienrf.json.derived

sealed trait Foo
case class Baz(id: String) extends Foo
...
implicit val frontendEventFormat: Format[FrontendEvent] = derived.oformat
`

When I compile this code, I get this error:
`
Error:(28, 69) could not find Lazy implicit value of type julienrf.json.derived.DerivedReads[A]
  implicit val frontendEventFormat: Format[FrontendEvent] = derived.oformat
`
What's going on?

**Comment by julienrf** [comment]
What is the definition of `FrontendEvent` ?

**Comment by danslapman** [comment]
@julienrf sorry, copypasted code from work project :) I meant
`implicit val fooFormat: Format[Foo] = derived.oformat`

**Comment by danslapman** [comment]
Hmm, just rewrote example from scratch, problem disappeared. I will investigate the reason more carefully

**Comment by julienrf** [comment]
OK, let me know if you encounter any issue!

**Comment by danslapman** [comment]
The reason was simple - I defined format value in another file
Quite scary

**Comment by julienrf** [comment]
The derivation process is based on shapeless derivation facilities, which are themselves based on the `knownDirectSubclasses` method of Scala reflection API. It is known that this method does not work in all situations, unfortunately… You can google it to find more details.

**Comment by resolve123** [comment]
after upgrading my sbt  version to 1.1.4 getting below error during build
could not find Lazy implicit value of type julienrf.json.derived.DerivedReads[A]
[error]   implicit val readsSparkMessage: Reads[SparkMessage] = derived.reads(NameAdapter.identity)
