### ISSUE TITLE
Support TypeTags for

### ISSUE THREAD

**Issue by sbrunk** [julienrf/play-json-derived-codecs#41]
I have a larger collection of case classes all extending a sealed trait. In order to avoid naming collisions in the code these case classes are grouped into different objects (could also be packages). Now it seems the typeName used for tagging in JSON is be only the class name, so things get mixed up in this case. See example below. Is there any way to control what is used as type tag? I haven't found anything so far.

``` scala
import julienrf.json.derived
import play.api.libs.json._

sealed trait Event

object Tabs { // could also be a package "tabs"
  case class OnCreated(foo: String) extends Event
  // other tab events
}

object Windows {
  case class OnCreated(foo: String) extends Event
  // other window events
}

object ConverterTest {
  def main(args: Array[String]): Unit = {
    implicit val eventFormat: Format[Event] = derived.oformat

    val tabOnCreated: Event = Tabs.OnCreated("tab created")
    val tabOnCreatedJson = Json.prettyPrint(Json.toJson(tabOnCreated))
    println(tabOnCreatedJson)
    println(Json.parse(tabOnCreatedJson).validate[Event].get.getClass)
    println

    val windowOnCreated: Event = Windows.OnCreated("window created")
    val windowOnCreatedJson = Json.prettyPrint(Json.toJson(windowOnCreated))
    println(windowOnCreatedJson)
    println(Json.parse(windowOnCreatedJson).validate[Event].get.getClass)
  }
}
```

Gives the following output:

```
{
  "OnCreated" : {
    "foo" : "tab created"
  }
}
class Tabs$OnCreated

{
  "OnCreated" : {
    "foo" : "window created"
  }
}
class Tabs$OnCreated
```

**Comment by julienrf** [comment]
Hi, thanks for reporting this.

One solution could be to use the fully qualified name of the variants, but that would break existing client code relying on the actual names.

**Comment by sbrunk** [comment]
Ideally this would be configurable similar to json4s [ShortTypeHints/FullTypeHints] (https://github.com/json4s/json4s#serializing-polymorphic-lists), using the existing behaviour as default for backwards-compatibility.

**Comment by henricook** [comment]
I'd also quite like to be able to pick my own values for the `type` field - so that renaming/refactoring a class doesn't accidentally break our persisted JSON data - do you know if anyone ever got around to this @julienrf ?

**Comment by julienrf** [comment]
Hello, we could get the type name from an implicit with a fallback to the current behavior. For instance:

~~~ scala
sealed trait Foo
case class Bar(s: String) extends Foo
case class Baz(i: Int) extends Foo

object Foo {
  implicit val barTypeTag: TypeTag[Bar] = TypeTag("Quux")

  implicit val format: OFormat[Foo] = derived.oformat
}
~~~

In this case, `Bar` would use `"Quux"` as a type tag, but `Baz` would use `"Baz"`.

Implementing this is doable but I’m not sure it is *desirable* because it makes the system more complex. If you want to control the type tag used and if you want your serialization format to be resilient to renamings, then you should probably write the serialization format by hand, no?

**Comment by henricook** [comment]
Possibly fair enough! Thanks for your thoughts on that

**Comment by henricook** [comment]
I agree that a TypeTag with an auto fallback would create scope for error, I definitely wouldn't want an auto fallback. I am keen for the safety of a hard coded type string to protect against a developer refactoring a class name and not realising (s)he's changed the data model though

**Comment by julienrf** [comment]
@henricook OK, I can make the type tag either always required or always inferred.

I would appreciate if users of this feature could financially support my work. Please consider posting a bounty at https://www.bountysource.com/issues/54399379-support-typetags-for.

**Comment by henricook** [comment]
Would be happy to! FWIW I have piggy backed @sbrunk 's ticket here but i'm not tied to TypeTags - if that's the easiest way then by all means, but really all I want is the ability to define a string somewhere :-D

Would the check to ensure TypeTags exist be compile time do you reckon?

**Comment by julienrf** [comment]
> Would the check to ensure TypeTags exist be compile time do you reckon?

Yes.

**Comment by julienrf** [comment]
I’ve just published a new version with this feature: https://github.com/julienrf/play-json-derived-codecs/releases

**Comment by henricook** [comment]
I've just rolled it into my project and it works beautifully, thanks Julien!

**Comment by tonyflow** [comment]
> Hello, we could get the type name from an implicit with a fallback to the current behavior. For instance:
> 
> ```scala
> sealed trait Foo
> case class Bar(s: String) extends Foo
> case class Baz(i: Int) extends Foo
> 
> object Foo {
>   implicit val barTypeTag: TypeTag[Bar] = TypeTag("Quux")
> 
>   implicit val format: OFormat[Foo] = derived.oformat
> }
> ```
> 
> In this case, `Bar` would use `"Quux"` as a type tag, but `Baz` would use `"Baz"`.
> 
> Implementing this is doable but I’m not sure it is _desirable_ because it makes the system more complex. If you want to control the type tag used and if you want your serialization format to be resilient to renamings, then you should probably write the serialization format by hand, no?

I'm not sure I understand how to define a custom name for my type tags.

I want my Json to follow this flat pattern
```
{
  "type": "Bar",
  "s": "quux",
  "i": 42
}
```
so I'm using this `OFormat`: 
```scala
implicit val oformat: OFormat[ColumnConfiguration] =
    julienrf.json.derived.flat.oformat[ColumnConfiguration](
      typeName = (__ \ "configType").format[String]
    )
```
which does not allow the configuration of any `TypeTagSetting`s

For a hierarchy like the following:

```scala
sealed trait A

object A {
 implicit val oformat: OFormat[A] =
    julienrf.json.derived.flat.oformat[A](
      typeName = (__ \ "configType").format[String]
    )
}

class B extends A
```

How should the `TypeTag` be configured?
Do I have to define a `TypeTagSetting` somewhere?
Do i have to define a `CustomTypeTag` in the companion object of the sealed trait or in the companion object of the extensions of the sealed trait?

I cannot find any answers to these questions in the documentation. There is a reference to `TypeTagSetting.UserDefined` name but I cannot use it with `derived.flat.oformat`.

Thanks a lot for your attention.

**Comment by julienrf** [comment]
You can specify both the `TypeTagOFormat` and the `TypeTagSetting` (see [API documentation](https://javadoc.io/static/org.julienrf/play-json-derived-codecs_2.13/6.0.0/julienrf/json/derived/package$$withTypeTag$.html)):

~~~ scala
implicit val oformat: OFormat[ColumnConfiguration] =
    julienrf.json.derived.withTypeTag.oformat[ColumnConfiguration](
      TypeTagSetting.UserDefinedName,
      typeTagOFormat = TypeTagOFormat.flat((__ \ "configType").format[String])
    )
~~~

You will also need an implicit [`CustomTypeTag`](https://javadoc.io/static/org.julienrf/play-json-derived-codecs_2.13/6.0.0/julienrf/json/derived/CustomTypeTag.html) instance for your constructor types.

Does that help?

**Comment by tonyflow** [comment]
My configuration now is the following
```scala
object A {
  implicit val oformat: OFormat[A] =
    julienrf.json.derived.withTypeTag.oformat(
      typeTagSetting = TypeTagSetting.UserDefinedName,
      typeTagOFormat = TypeTagOFormat.flat((__ \ "configType").format[String])
    )

  implicit val literal:CustomTypeTag[B] = CustomTypeTag[B]("is a b")
}

case class C(name:String, columns:Vector[A])

object C {
  implicit val writes: Writes[C] = Json.writes[C]
}
```
and the error I am getting is the following:
```
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:424)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:209)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	... 27 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at models.api.dto.C$.<init>(Configuration.scala:137)
	at models.api.dto.C$.<clinit>(Configuration.scala)
	at controllers.api.SomeController.$anonfun$getSomeConfiguration$1(SomeController.scala:135)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
	... 32 common frames omitted
Caused by: java.lang.NullPointerException: null
	at julienrf.json.derived.TypeTag$UserDefinedName$$anon$8.value(typetags.scala:186)
	at julienrf.json.derived.DerivedReadsInstances$$anon$2.reads(DerivedReads.scala:39)
	at julienrf.json.derived.DerivedReadsInstances2$$anon$6.reads(DerivedReads.scala:93)
	at julienrf.json.derived.package$withTypeTag$.oformat(package.scala:101)
	at models.api.dto.A$.<init>(Configuration.scala:119)
	at models.api.dto.A$.<clinit>(Configuration.scala)
	... 38 common frames omitted

```

**Comment by julienrf** [comment]
Does that clear the error if you move the `literal` implicit val definition *before* the `oformat` definition? The `oformat` definition does use `literal` (by implicit resolution), that’s why `literal` has to be initialized before `oformat`.

**Comment by tonyflow** [comment]
Thank you so very much @julienrf . Your answers were prompt and to the point. Both of them fixed my problem!
