### ISSUE TITLE
Flat representation

### ISSUE THREAD

**Issue by tasuk** [julienrf/play-json-derived-codecs#45]
The flat representation is nice: https://github.com/julienrf/play-json-derived-codecs/#custom-representation-of-sum-types

1. I get `not found: value __` on `derived.flat.owrites((__ \ "type").write[String])` ... how is this magic supposed to work?

2. The readme only mentions writes - how to do reads in the same format? Or even better - both reads and writes in one definition?

Thank you!

**Comment by julienrf** [comment]
- `__` comes from Play: https://www.playframework.com/documentation/2.5.x/api/scala/index.html#play.api.libs.json.package@__:play.api.libs.json.JsPath.type
- It works the same with `Reads` and `OFormat`: https://static.javadoc.io/org.julienrf/play-json-derived-codecs_2.11/3.3/index.html#julienrf.json.derived.package$$flat$@oformat[A](typeName:play.api.libs.json.OFormat[String])(implicitderivedReads:shapeless.Lazy[julienrf.json.derived.DerivedReads[A]],implicitderivedOWrites:shapeless.Lazy[julienrf.json.derived.DerivedOWrites[A]]):play.api.libs.json.OFormat[A] : just supply the `OFormat` to use to encode and decode the type tag.

Does that help?

**Comment by tasuk** [comment]
Julien, thank you for your very fast answer. I'm sure the links are very helpful (the first one is for sure!), but I'm just the prototypical dumb user and don't care much about figuring out how this works - I just want it to work.

In the readme, you provide a great example how to represent `Bar("quux", 42)` as:

```
{
  "type": "Bar",
  "s": "quux",
  "i": 42
}
```

with:

```
implicit val fooOWrites: OWrites[Foo] =
  derived.flat.owrites((__ \ "type").write[String])
```

That's awesome! Could you please also provide an example of how to turn:
```
{
  "type": "Bar",
  "s": "quux",
  "i": 42
}
```

into: `Bar("quux", 42)` ?

I suppose it'd start like:

```
implicit val fooReads: Reads[Foo] = ???
```

I realize this is perhaps not what is covered by your library, but it is something the users of your library need to know how to do. I am attempting to be a user of your library and have no idea :)

**Comment by julienrf** [comment]
Hi, I’m sorry Tasuk but I will ask you to read the documentation. That’s a basic feature that will be useful to you anyway. I can not take time to fix problems of other people.

**Comment by tasuk** [comment]
Btw, this is not (just) about me. I thought "taking time to fix problems of other people" was the whole raison-d-etre of `play-json-derived-codecs`.

**Comment by ALenfant** [comment]
Thanks for the help. I had the same issue and I just had to add import play.api.libs.json.__ for it to work
