### ISSUE TITLE
Cross-compile to Scala 2.12

### ISSUE THREAD

**Issue by rpiaggio** [julienrf/play-json-derived-codecs#47]
Can you add support for Scala 2.12? Thank you!

**Comment by ikamthania** [comment]
Did a libraries version upgrade in [this](https://github.com/julienrf/play-json-derived-codecs/pull/48) pull request.

**Comment by rpiaggio** [comment]
Thank you @ikamthania !

**Comment by rpiaggio** [comment]
@julienrf May I ask if you planning a new release soon? Thank you!

**Comment by julienrf** [comment]
There were a bunch of issues I wanted to fix before a new release, but as a matter of fact I don’t have much time to work on it, so maybe I could do a new release soon so that users can benefit from Scala 2.12, Scala.js and Play 2.6 support…

**Comment by rpiaggio** [comment]
@julienrf That would be very much appreciated, thank you!
