### ISSUE TITLE
Publish recent version on maven central

### ISSUE THREAD

**Issue by rklaehn** [julienrf/play-json-derived-codecs#49]
It seems that the latest artifact on manven central is from April 2016.

**Comment by julienrf** [comment]
Few changes happened since then. I’m waiting for Play 2.6 to be released and then I’ll release a new version.

**Comment by julienrf** [comment]
FWIW I published a 4.0.0-RC1: https://index.scala-lang.org/julienrf/play-json-derived-codecs/play-json-derived-codecs/4.0.0-RC1?target=_2.12
