### ISSUE TITLE
Do milestone release for Scala 2.12

### ISSUE THREAD

**Issue by sarahgerweck** [julienrf/play-json-derived-codecs#51]
Is there any chance that you can do a milestone release with Play 2.6 and Scala 2.12, so that people who are tracking the Play 2.6 milestones and testing Scala 2.12 will also have access to this library without having to create and maintain their own build artifacts?

Alternately, one thing I've done with my own libraries is to use different dependency versions for different Scala versions. E.g., you could do a 3.4 release that cross compiled with Play 2.5 for Scala 2.11 and Play 2.6-M3 for Scala 2.12.

**Comment by julienrf** [comment]
Yeah, you’re right. I just published a 4.0.0-RC1 revision: https://index.scala-lang.org/julienrf/play-json-derived-codecs/play-json-derived-codecs/4.0.0-RC1?target=_2.12

**Comment by sarahgerweck** [comment]
Thanks @julienrf! :smile:
