### ISSUE TITLE
Add support for Play 2.6

### ISSUE THREAD

**Issue by palmerabollo** [julienrf/play-json-derived-codecs#52]
Play 2.6 was released some days ago. It would be great to support/build an artefact for it, too

**Comment by julienrf** [comment]
Yes, I agree! We could add support for Scala.js too :)

I don’t have time to work on that but pull requests are welcome!

**Comment by sarahgerweck** [comment]
I've opened #53, which I believe has all the changes that should be required to cut a final 4.0.0 release.

**Comment by sarahgerweck** [comment]
FYI @palmerabollo, the 4.0.0-RC1 release works fine with Play 2.6.

**Comment by julienrf** [comment]
I just published a 4.0.0 version!
