### ISSUE TITLE
What package should I import to get implicit value of type `Lazy[DerivedReads[...]]`? 

### ISSUE THREAD

**Issue by voroninp** [julienrf/play-json-derived-codecs#58]
Sorry, I am not experienced in Scala at all, but what should I import to get rid of the compiler error?

> Error:(12, 37) could not find Lazy implicit value of type julienrf.json.derived.DerivedReads[TaggedUnion]

**Comment by julienrf** [comment]
This means that play-json-derived-codecs has been unable to compute a decoder for your type. Can you minimize the problem and share it here?

**Comment by voroninp** [comment]
Well, I just wanted to check how it handles serialisation of a tagged union:
```
  sealed trait TaggedUnion
  case class Option1(index: Int) extends TaggedUnion
  case class Option2(name: String) extends TaggedUnion

  implicit val reads = derived.reads[TaggedUnion]
  implicit val writes = derived.owrites[TaggedUnion]

  "Codecs" should {
    "serialize tagged union" in {
      val option1 = Json.toJson(Option1(1))
      val option2 = Json.toJson(Option2("str"))
    }
  }

So my expectation here is that having `reads` for the trait should be enough for serialisation/deserialisation to work.

**Comment by julienrf** [comment]
That use case should work, we have a similar test case:

https://github.com/julienrf/play-json-derived-codecs/blob/master/library/src/test/scala/julienrf/json/derived/DerivedOFormatSuite.scala#L28-L51

Is that exactly the code you wrote?

**Comment by julienrf** [comment]
You should either use one `OFormat` or both a `Reads` and an `OWrites`. What happens if you comment the `OFormat` line?

**Comment by voroninp** [comment]
Same error. Btw, here is the reference in SBT if it matters `"org.julienrf" %% "play-json-derived-codecs" % "3.3"`

**Comment by julienrf** [comment]
Then you have to debug with the `-Xlog-implicits` compiler option to know what happens in your specific case.

**Comment by voroninp** [comment]
Hm...

>Information:(13, 37) shapeless.this.DefaultSymbolicLabelling.mkDefaultSymbolicLabelling is not a valid implicit value for shapeless.DefaultSymbolicLabelling.Aux[TaggedUnionDeserializationSpec.this.TaggedUnion,K] because:
hasMatchingSymbol reported error: **Sealed trait TaggedUnionDeserializationSpec.this.TaggedUnion has no case class subtypes**
  implicit val reads = derived.reads[TaggedUnion]
Information:(13, 37) shapeless.this.LabelledGeneric.materializeCoproduct is not a valid implicit value for shapeless.LabelledGeneric.Aux[TaggedUnionDeserializationSpec.this.TaggedUnion,R] because:
hasMatchingSymbol reported error: could not find implicit value for parameter lab: shapeless.DefaultSymbolicLabelling.Aux[TaggedUnionDeserializationSpec.this.TaggedUnion,K]
  implicit val reads = derived.reads[TaggedUnion]
Information:(13, 37) shapeless.this.LabelledGeneric.materializeProduct is not a valid implicit value for shapeless.LabelledGeneric.Aux[TaggedUnionDeserializationSpec.this.TaggedUnion,R] because:
hasMatchingSymbol reported error: could not find implicit value for parameter lab: shapeless.DefaultSymbolicLabelling.Aux[TaggedUnionDeserializationSpec.this.TaggedUnion,K]
  implicit val reads = derived.reads[TaggedUnion]
Information:(13, 37) derived.this.DerivedReads.readsGeneric is not a valid implicit value for julienrf.json.derived.DerivedReads[TaggedUnionDeserializationSpec.this.TaggedUnion] because:
hasMatchingSymbol reported error: could not find implicit value for parameter gen: shapeless.LabelledGeneric.Aux[TaggedUnionDeserializationSpec.this.TaggedUnion,R]
  implicit val reads = derived.reads[TaggedUnion]
Information:(13, 37) shapeless.this.Lazy.mkLazy is not a valid implicit value for shapeless.Lazy[julienrf.json.derived.DerivedReads[TaggedUnionDeserializationSpec.this.TaggedUnion]] because:
hasMatchingSymbol reported error: Unable to derive julienrf.json.derived.DerivedReads[TaggedUnionDeserializationSpec.this.TaggedUnion]
  implicit val reads = derived.reads[TaggedUnion]
Error:(13, 37) could not find Lazy implicit value of type julienrf.json.derived.DerivedReads[TaggedUnionDeserializationSpec.this.TaggedUnion]
  implicit val reads = derived.reads[TaggedUnion]
Information:(13, 37) shapeless.this.Lazy.apply is not a valid implicit value for (=> Unit) => shapeless.Lazy[julienrf.json.derived.DerivedReads[TaggedUnionDeserializationSpec.this.TaggedUnion]] because:
type mismatch;
 found   : Unit
 required: julienrf.json.derived.DerivedReads[TaggedUnionDeserializationSpec.this.TaggedUnion]
 Note: implicit value reads is not applicable here because it comes after the application point and it lacks an explicit result type
  implicit val reads = derived.reads[TaggedUnion]
Error:(13, 37) not enough arguments for method reads: (implicit derivedReads: shapeless.Lazy[julienrf.json.derived.DerivedReads[TaggedUnionDeserializationSpec.this.TaggedUnion]])play.api.libs.json.Reads[TaggedUnionDeserializationSpec.this.TaggedUnion].
Unspecified value parameter derivedReads.
  implicit val reads = derived.reads[TaggedUnion]
Error:(18, 32) No Json serializer found for type TaggedUnionDeserializationSpec.this.Option1. Try to implement an implicit Writes or Format for this type.
      val option1 = Json.toJson(Option1(1))
Error:(18, 32) not enough arguments for method toJson: (implicit tjs: play.api.libs.json.Writes[TaggedUnionDeserializationSpec.this.Option1])play.api.libs.json.JsValue.
Unspecified value parameter tjs.
      val option1 = Json.toJson(Option1(1))

**Comment by julienrf** [comment]
Ah OK, that’s a limitation of the macros used under hood…
