### ISSUE TITLE
Support Play 2.8

### ISSUE THREAD

**Issue by inigo** [julienrf/play-json-derived-codecs#69]
Play 2.8 is now out as of 13th December, and play-json-derived isn't compatible with it.

Can you do a Play 2.8 build, please?

**Comment by julienrf** [comment]
Sure, do you mind opening a pull request for that?

**Comment by inigo** [comment]
I'll try - although my initial naive "just import the Play 2.8 libraries" attempt failed to compile, so it will require at least something in addition to that.

**Comment by julienrf** [comment]
Cool! I’m happy to help if you are stuck with some errors.
