### ISSUE TITLE
Mismatched Reads/Writes when using custom formats

### ISSUE THREAD

**Issue by ncreep** [julienrf/play-json-derived-codecs#76]
Hi,

After the merging of #75, there's a new edge-case that wasn't considered in that pull-request. One where you get mismatching `Reads`/`Writes` instances.

Consider the following:
```scala
sealed trait Foo
case class Bar(x: Int) extends AnyVal

object Bar { implicit val format: Format[Bar] = Json.valueFormat }

object Foo {
  implicit val format: Format[Foo] = derived.oformat()
}
```

Now, since `Bar` has a `Reads` instance, `derived` picks it up for reading. But since `Bar` doesn't have an `OWrites` instance, just a `Writes`, `derived` generates one on-the-fly. The generated `OWrites` is not compatible with the custom `Reads`, so writing and then reading will produce an error. In this case there's no way for the user to provide an `OWrites` and this failure mode is completely silent.

My question is, what can be done about it?

The reason why `derived` only operates on `OWrites` is due to `derived.flat` requiring an `OWrites` in `TypeTagOWrites`. Nested formats could do without it.

One possible solution would be to lift the restriction from `TypeTagOWrites` and allow `Writes`. Then in `derived.flat` we can inspect the result of the `Writes` that was provided, if it's a `JSObject` continue the same as today, and if it's not create a wrapper:
```scala
{ "type": "Bar", "value": ... }
```
Where the `value` field is generated synthetically. This somewhat breaks the point of `flat`, but I think it's less of a failure then what I've shown above (and it's an edge case).

Another direction would be to completely separate `flat` from the nested format, not sure how much effort/duplication that would yield.

Are there any other suggestions?

Thanks

**Comment by julienrf** [comment]
Would it work to replace `Format` with `OFormat` in your example?

**Comment by ncreep** [comment]
Yes, with an `OFormat` it would work as expected.

**Comment by a1kemist** [comment]
I just ran into this and was wondering why I suddenly had a ton of deser exceptions related to case objects in a sealed ADT hierarchy that uses the flat format.

Using the `OFormat` instance does "fix" the issue, but it would be good to either add a notice to the readme/changelog or something along the lines of what @ncreep has suggested considering that existing code now behaves differently when using the latest version.
