### ISSUE TITLE
Adding type tags to individual case classes

### ISSUE THREAD

**Issue by jmccance** [julienrf/play-json-derived-codecs#87]
With a plain case class, I was expecting `withTypeTag` to add `_type` tag to the output:

```scala
import julienrf.json.derived
import julienrf.json.derived._

case class Widget(id: Long, name: String)

val derivedFormat = derived.withTypeTag.oformat[Widget](TypeTagSetting.ShortClassName)

val widget = Widget(42, "Flange")

derivedFormat.writes(widget) 
// EXPECTED: {"id":42,"name":"Flange","_type": "Widget"}
// ACTUAL: {"id":42,"name":"Flange"}
```

**USE CASE**

The reason I was looking for this behavior was to support schema evolution. We're persisting JSON that we may need to break out into sealed traits in the future. To make this simpler, we'd like these case classes to just have the `_type` tag from the very beginning so we don't have to do anything fancy when we eventually do split them out.

**Comment by julienrf** [comment]
Type tags are added to sealed hierarchies only, not to classes. What you can do is:

~~~ scala
sealed trait WidgetType
case class Widget(id: Long, name: String) extends WidgetType
~~~

**Comment by jmccance** [comment]
Apologies for letting this linger. I was hoping to be able to get the type tag without having to introduce a sealed trait, since it complicates dealing with `Widget`. E.g., if we use `WidgetType` places, then we can't access fields or methods on `Widget` without either mirroring them onto WidgetType or doing pattern matching.

Won't necessarily be able to tackle this soon, but would you be open to a PR that allowed `withTypeTag` on a plain case class to add the type tag to the serialized payload? Or is this not a feature you would like in the library?

**Comment by julienrf** [comment]
Hey, to be honest, I don’t have much time to work on this project, so I prefer not adding new features unless there is high demand. I hope you understand :)

**Comment by jmccance** [comment]
Totally understand. Thanks for being open about it!
