### ISSUE TITLE
Casing mismatch

### ISSUE THREAD

**Issue by GeluOltean** [julienrf/play-json-derived-codecs#88]
Hi Julien,

I recently started using the library and I noticed that when tagging the types, the naming strategies from `NameAdapter` are only applied to the class fields. In my case, for compatibility, I need to (de)serialize the fields as well as the class tags in snake_case.

For example, given this class hierarchy:
 ```scala
sealed trait DemoClass
final case class ClassOne(fieldOne: String, fieldTwo: String) extends DemoClass
final case class ClassTwo(nested: DemoClass, fieldOne: String, fieldTwo: String) extends DemoClass

val classOne: DemoClass = ClassOne("field one", "field two")
val classTwo: DemoClass = ClassTwo(classOne, "field one", "field two")
```

And using this `OFormat` for conversion:
```scala
implicit val demoClassFormat: OFormat[DemoClass] = derived
    .withTypeTag
    .oformat[DemoClass](TypeTagSetting.FullClassName, NameAdapter.snakeCase)
```

The resulting JSON is the following:
```JSON
{
  "ClassTwo" : {
    "nested" : {
      "ClassOne" : {
        "field_one" : "field one",
        "field_two" : "field two"
      }
    },
    "field_one" : "field one",
    "field_two" : "field two"
  }
}
```

With `ClassOne` and `ClassTwo` remaining CamelCase. 

Considering this, I'd like to add the feature of snake_casing type tags and open a pull request, if that's alright with you. Currently the code I use in my projects is an additional `TypeTagSetting` with the related classes, but maybe it would be worth considering applying this automatically whenever `NameAdapter.snakeCase` is used as an argument in `withTypeTag.oformat`.

I made a repo with an example that shows the current behavior and how it would be modified by the additional `TypeTagSetting`, [available here](https://github.com/GeluOltean/play-json-derived-snakecase-demo).

Thanks!

**Comment by julienrf** [comment]
Hi, thank you for the detailed description. If I understand correctly, you only need to introduce a new value for `TypeTagSetting`? That sounds reasonable! I’m happy to review a PR.
